name: flutter_tech_task
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  
  http: ^1.5.0
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^3.0.0
  riverpod_annotation: ^3.0.0
  google_fonts: ^6.3.1  
  mocktail: ^1.0.4  

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  custom_lint:
  riverpod_generator: ^3.0.0
  riverpod_lint: ^3.0.0  

flutter:
  uses-material-design: true
